version: "3.9"

services:
  credit:
    container_name: credit.in-duck-tor
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GH_USERNAME
        - GH_TOKEN
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - in-duck-tor

volumes:
  credit-postgres:

networks:
  in-duck-tor:
    name: in-duck-tor
    external: true